[package]
name = "dbug"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.13.1"
mini-server = "0.2.0"
syntect = "5.2.0"
serde_json = "1.0"
storage = "0.1"  # Assuming a storage crate exists
serde = { version = "1.0", features = ["derive"] }
